---

- hosts: all
  become: true
  vars_files:
    - vars/passwd.yml
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Install Python PostgreSQL library
      apt:
        name: python3-psycopg2
        state: present

    - name: Create database
      postgresql_db:
        name: prod_db
      become: true
      become_user: postgres

    - name: Create user
      postgresql_user:
        name: admin
        password: "{{ vault_postgres_admin_password }}"
        db: prod_db
        role_attr_flags: SUPERUSER
      become: true
      become_user: postgres

    - name: Enable pg_cron in PostgreSQL configuration
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?shared_preload_libraries ='
        line: "shared_preload_libraries = 'pg_cron'"
        state: present
      
    - name: Allow PostgreSQL to listen on all interfaces
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
        state: present
        
    - name: Allow remote connections in pg_hba.conf
      blockinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        marker: "# {mark} Ansible managed block for remote access"
        block: |
          host    all             all             0.0.0.0/0            md5
          host    all             all             ::/0                 md5

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

    - name: Create pg_cron extension
      postgresql_query:
        db: postgres
        query: "CREATE EXTENSION IF NOT EXISTS pg_cron;"
      become: true
      become_user: postgres

        
    - name: Create tables in the db
      postgresql_query:
        db: prod_db
        query: "{{ lookup('file', 'queries/documed_ddl.sql') }}"
      become: true
      become_user: postgres

    - name: Schedule cron jobs using existing SQL file
      postgresql_query:
        db: postgres
        query: "{{ lookup('file', 'queries/documed_cron_jobs.sql') }}"
      become: true
      become_user: postgres

