---

- hosts: all
  become: true
  vars_files:
    - vars/passwd.yml

  tasks:
    - name: Install PostgreSQL and required packages
      apt:
        name:
          - postgresql
          - postgresql-15-cron
          - python3-psycopg2
        state: present
        update_cache: true

    - name: Allow PostgreSQL to listen on all interfaces
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"
        state: present

    - name: Enable pg_cron in shared_preload_libraries
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?shared_preload_libraries\s*='
        line: "shared_preload_libraries = 'pg_cron'"
        state: present

    - name: Set pg_cron database in postgresql.conf
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?cron\.database_name\s*='
        line: "cron.database_name = 'test_db'"
        state: present

    - name: Allow remote connections in pg_hba.conf
      blockinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        marker: "# {mark} Ansible managed block for remote access"
        block: |
          host    all             all             0.0.0.0/0            md5
          host    all             all             ::/0                 md5

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
        
    - name: Create database
      postgresql_db:
        name: prod_db
      become_user: postgres

    - name: Create database
      postgresql_db:
        name: test_db
      become_user: postgres
      
    - name: Create user
      postgresql_user:
        name: admin
        password: "{{ vault_postgres_admin_password }}"
        db: prod_db
        role_attr_flags: SUPERUSER
      become: true
      become_user: postgres

    - name: Create user
      postgresql_user:
        name: admin
        password: "{{ vault_postgres_admin_password }}"
        db: test_db
        role_attr_flags: SUPERUSER
      become_user: postgres

    - name: Create pg_cron extension in test_db
      postgresql_query:
        db: test_db
        query: "CREATE EXTENSION IF NOT EXISTS pg_cron;"
      become_user: postgres

    - name: Create tables in the test_db
      postgresql_query:
        db: test_db
        query: "{{ lookup('file', 'queries/documed_ddl.sql') }}"
      become: true
      become_user: postgres

    - name: Create tables in the prod_db
      postgresql_query:
        db: prod_db
        query: "{{ lookup('file', 'queries/documed_ddl.sql') }}"
      become: true
      become_user: postgres
      