---

- hosts: all
  become: true
  vars_files:
    - vars/passwd.yml
    
  vars:
    prod_db_name: "prod_db"
    test_db_name: "test_db"
    backup_dir: "/var/backups/postgresql"
    pg_dump_path: "/usr/bin/pg_dump"
    admin_password_hash: "$2a$10$2bv1RJMphiI3vSubTl9Q3OJg7ukLpsLU6V6j5/ueyG2LnVRUHS4MS"  # hash for 'Password123' in bcrypt
    admin_email: "admin@gmail.com"

  tasks:
    - name: Install PostgreSQL and required packages
      apt:
        name:
          - postgresql
          - postgresql-15-cron
          - python3-psycopg2
        state: present
        update_cache: true

    - name: Allow PostgreSQL to listen on all interfaces
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"
        state: present
        
    - name: Calculate 25% of total RAM in MB
      set_fact:
        shared_buffers_value: "{{ ((ansible_facts.memtotal_mb * 0.25) | int) }}MB"
        
    - name: Set shared_buffers in postgresql.conf to 25% of RAM memory
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?shared_buffers\s*='
        line: "shared_buffers = {{ shared_buffers_value }}"
        state: present

    - name: Enable pg_cron in shared_preload_libraries
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?shared_preload_libraries\s*='
        line: "shared_preload_libraries = 'pg_cron'"
        state: present

    - name: Allow remote connections in pg_hba.conf
      blockinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        marker: "# {mark} Ansible managed block for remote access"
        block: |
          host    all             all             0.0.0.0/0            md5
          host    all             all             ::/0                 md5

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
        
    - name: Create databases
      postgresql_db:
        name: "{{ item }}"
      become_user: postgres
      loop:
        - "{{ prod_db_name }}"
        - "{{ test_db_name }}"
      
    - name: Create admin user in both databases
      postgresql_user:
        name: admin
        password: "{{ vault_postgres_admin_password }}"
        db: "{{ item }}"
        role_attr_flags: SUPERUSER
      become_user: postgres
      loop:
        - "{{ prod_db_name }}"
        - "{{ test_db_name }}"

    - name: Ensure cron is installed
      package:
        name: cron
        state: present

    - name: Set pg_cron database in postgresql.conf
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?cron\.database_name\s*='
        line: "cron.database_name = '{{ prod_db_name }}'"
        state: present

    - name: Create pg_cron extension in production database only
      postgresql_query:
        db: "{{ prod_db_name }}"
        query: "CREATE EXTENSION IF NOT EXISTS pg_cron;"
      become_user: postgres

    - name: Create tables in both databases
      postgresql_query:
        db: "{{ item }}"
        query: "{{ lookup('file', 'queries/documed_ddl.sql') }}"
      become_user: postgres
      loop:
        - "{{ prod_db_name }}"
        - "{{ test_db_name }}"

    - name: Insert admin user into prod_db
      postgresql_query:
        db: "{{ prod_db_name }}"
        query: >
          INSERT INTO "User" (
            first_name, last_name, pesel, passport_number, email, address, password,
            phone_number, account_status, birthdate, pwz, role, subscription_id, email_notifications
          )
          VALUES (
            'Admin', 'Adminski', NULL, NULL, '{{ admin_email }}', NULL,' {{ admin_password_hash }}'
            ,'000000000', 'ACTIVE', '1990-01-01',
            NULL, 'ADMINISTRATOR', NULL, true
          );
      become_user: postgres

    - name: Create pgbackup group
      group:
        name: pgbackup
        state: present

    - name: Add postgres and admin to pgbackup group
      user:
        name: "{{ item }}"
        groups: pgbackup
        append: yes
      loop:
        - postgres
        - admin

    - name: Ensure backup directory exists with secure permissions
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: postgres
        group: pgbackup
        mode: '0750'

    - name: Schedule weekly pg_dump backup via cron on Sunday at 2:00 on prod_db
      cron:
        name: "Weekly PostgreSQL backup"
        user: postgres 
        minute: "0"
        hour: "2"
        weekday: "0"
        job: >-
          /bin/bash -c '
          export PATH=/usr/bin:/bin;
          {{ pg_dump_path }} -Fc -d {{ prod_db_name }} -f "{{ backup_dir }}/{{ prod_db_name }}_$(date +\%F_\%H\%M\%S).dump"
          ' >> {{ backup_dir }}/backup.log 2>&1
      
    - name: Schedule jobs in all databases from production DB
      postgresql_query:
        db: "{{ prod_db_name }}"
        query: "{{ lookup('file', 'queries/documed_cron_jobs.sql') | replace('%TARGET_DB%', item) }}"
      become_user: postgres
      loop:
        - "{{ prod_db_name }}"
        - "{{ test_db_name }}"
    
      
